# Generated by Django 4.2.2 on 2023-06-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='user',
        ),
    ]
